#! /bin/sh -e
# This file is automatically generated with: tup generate build.sh
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
(./xxdfor fragment.glsl vertex.glsl > embed.h)
(g++ -c -o newton-fractal.o -Wall -Werror `pkg-config --cflags sdl2 glew` newton-fractal.cc)
(g++ -o newton-fractal -Wall -Werror newton-fractal.o `pkg-config --libs sdl2 glew` -lm)
