#! /bin/sh -e
# This file is automatically generated with: tup generate build.sh
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
(./xxdfor fragment.glsl vertex.glsl > embed.h)
(g++ -o newton-fractal -Wall -Werror `pkg-config --cflags --libs sdl2 glew` -lm newton-fractal.cc)
